quarkus.http.port=8080
quarkus.application.name=saga-orchestrator

# ==========================================
# CONFIGURACIÓN GENERAL / PRODUCCIÓN / DEV
# ==========================================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_JDBC_URL}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.devservices.enabled=false
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

# Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

# Clientes REST distribuidos
quarkus.rest-client.account-api.url=http://localhost:8081
quarkus.rest-client.payment-api.url=http://localhost:8082
quarkus.rest-client.notification-api.url=http://localhost:8083

# ==========================================
# PERFIL DE TEST (%test)
# Se activa únicamente al ejecutar ./mvnw test
# ==========================================
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:orchestrator_test;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.log.sql=false

# URLs simuladas para testing (serán interceptadas por los mocks)
%test.quarkus.rest-client.account-api.url=http://localhost:8081
%test.quarkus.rest-client.payment-api.url=http://localhost:8082
%test.quarkus.rest-client.notification-api.url=http://localhost:8083