quarkus.http.port=8081
quarkus.application.name=account-service

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DB_JDBC_URL}
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}

quarkus.devservices.enabled=false
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false